{config, pkgs, ... }:

{
  imports = [ ./hardware-configuration.nix ];

 # Bootloader.
 boot = {                                      # Boot Options
    loader = {
      systemd-boot = {
        enable = true;
        configurationLimit = 5;
      };
      efi.efiSysMountPoint = "/boot";
      efi.canTouchEfiVariables = true;
      timeout = 1;
    };
    kernelPackages =  pkgs.linuxPackages_latest;
    initrd.kernelModules = [ "amdgpu" ];        # Video Drivers
    
  };


services.unifi.enable = true;

  
 services.xserver.displayManager.startx.enable = true;


 networking.hostName = "desktop"; # Define your hostname.
networking.hostId = "2245754b";
 hardware = {
    opengl = {                                  # Hardware Accelerated Video
      enable = true;
      extraPackages = with pkgs; [
        mesa.drivers
	libvdpau-va-gl
        rocm-opencl-icd
        rocm-opencl-runtime
        amdvlk
      ];
      extraPackages32 = with pkgs; [
        driversi686Linux.amdvlk
      ];
      driSupport = true;
      driSupport32Bit = true;
    };
    sane = {                                    # Scanning
      enable = true;
      extraBackends = [ pkgs.sane-airscan ];
    };
  };


#hyprland.enable = true;
gnome.enable = true;
#services.xserver.displayManager.gdm.enable = true;
#services.xserver.desktopManager.gnome.enable = true;
  
  environment = {
    systemPackages = with pkgs; [               # System-Wide Packages
      plex-media-player # Media Player
      simple-scan       # Scanning
      lm_sensors
      cifs-utils
    ];
  };

#hardware.fancontrol.enable = true;

#hardware.fancontrol.config = ''
# Configuration file generated by pwmconfig, changes will be lost
#INTERVAL=10
#DEVPATH=hwmon0=devices/pci0000:00/0000:00:02.3/0000:04:00.0
#DEVNAME=hwmon0=amdgpu
#FCTEMPS= hwmon0/pwm1=hwmon0/temp1_input
#FCFANS= hwmon0/pwm1=hwmon0/fan1_input
#MINTEMP= hwmon0/pwm1=45
#MAXTEMP= hwmon0/pwm1=75
#MINSTART= hwmon0/pwm1=150
#MINSTOP= hwmon0/pwm1=0
#MAXPWM= hwmon0/pwm1=255
#'';

fileSystems."/home/stephan/Nextcloud" = {
    device = "//10.10.10.70/Netcup";
    fsType = "cifs";
    options = let
      # this line prevents hanging on network split
      automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";

    in ["${automount_opts},credentials=/etc/nixos/smb-secrets,uid=1000,gid=100"];
  };

 

}
