{config, pkgs, ... }:

{
  imports = [ ./hardware-configuration.nix ];

 # Bootloader.
 boot = {                                      # Boot Options
    loader = {
      systemd-boot = {
        enable = true;
        configurationLimit = 5;
      };
      efi.efiSysMountPoint = "/boot";
      efi.canTouchEfiVariables = true;
      timeout = 1;
    };
    kernelPackages = pkgs.linuxPackages_latest;
    initrd.kernelModules = [ "amdgpu" ];        # Video Drivers
  };

  
 networking.hostName = "desktop"; # Define your hostname.

 hardware = {
    opengl = {                                  # Hardware Accelerated Video
      enable = true;
      extraPackages = with pkgs; [
        intel-media-driver
        vaapiIntel
        rocm-opencl-icd
        rocm-opencl-runtime
        amdvlk
      ];
      extraPackages32 = with pkgs; [
        driversi686Linux.amdvlk
      ];
      driSupport = true;
      driSupport32Bit = true;
    };
    sane = {                                    # Scanning
      enable = true;
      extraBackends = [ pkgs.sane-airscan ];
    };
  };
 
hyprland.enable = true;
  
  environment = {
    systemPackages = with pkgs; [               # System-Wide Packages
      plex-media-player # Media Player
      simple-scan       # Scanning
      lm_sensors
    ];
  };

hardware.fancontrol.enable = true;

hardware.fancontrol.config = ''
# Configuration file generated by pwmconfig, changes will be lost
INTERVAL=10
DEVPATH=hwmon0=devices/pci0000:00/0000:00:02.3/0000:05:00.0
DEVNAME=hwmon0=amdgpu
FCTEMPS= hwmon0/pwm1=hwmon0/temp1_input
FCFANS= hwmon0/pwm1=hwmon0/fan1_input
MINTEMP= hwmon0/pwm1=45
MAXTEMP= hwmon0/pwm1=75
MINSTART= hwmon0/pwm1=150
MINSTOP= hwmon0/pwm1=0
MAXPWM= hwmon0/pwm1=255
'';


}
